Prefix: '&7[&3JumpDown&7]'
Nachrichten:
  Isonground: '%PREFIX% %PLAYER% ist unten angekommen'
  Todkiller: '%PREFIX% %PLAYER% wurde von %KILLER% getoetet'
  Nextround: '%PREFIX% Bereit machen fuer naechste Runde'
  Vorbei: '%PREFIX% &cDas Spiel ist vorbei.'
  Nichtgenug: '%PREFIX% Nicht genung Spieler. Countdown wird zurueckgesetzt.'
  Rundenbeginn: '&cDie Runde laeuft schon'
  Noperm: '%PREFIX% Keine Berechtigung'
  Runde1: ' &eGewinner der ersten Runde &7| %PLAYER%'
  Runde2: ' &eGewinner der zweiten Runde &7| %PLAYER%'
  Runde3: ' &eGewinner der dritten Runde &7| %PLAYER%'
Quit:
  Wenn23: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a23&8/&a%LIMIT%&8)'
  Wenn22: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a22&8/&a%LIMIT%&8)'
  Wenn21: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a21&8/&a%LIMIT%&8)'
  Wenn20: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a20&8/&a%LIMIT%&8)'
  Wenn19: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a19&8/&a%LIMIT%&8)'
  Wenn18: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a18&8/&a%LIMIT%&8)'
  Wenn17: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a17&8/&a%LIMIT%&8)'
  Wenn16: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a16&8/&a%LIMIT%&8)'
  Wenn15: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a15&8/&a%LIMIT%&8)'
  Wenn14: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a14&8/&a%LIMIT%&8)'
  Wenn13: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a13&8/&a%LIMIT%&8)'
  Wenn12: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a12&8/&a%LIMIT%&8)'
  Wenn11: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a11&8/&a%LIMIT%&8)'
  Wenn10: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a10&8/&a%LIMIT%&8)'
  Wenn9: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a9&8/&a%LIMIT%&8)'
  Wenn8: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a8&8/&a%LIMIT%&8)'
  Wenn7: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a7&8/&a%LIMIT%&8)'
  Wenn6: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a6&8/&a%LIMIT%&8)'
  Wenn5: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a5&8/&a%LIMIT%&8)'
  Wenn4: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a4&8/&a%LIMIT%&8)'
  Wenn3: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a3&8/&a%LIMIT%&8)'
  Wenn2: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a2&8/&a%LIMIT%&8)'
  Wenn1: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a1&8/&a%LIMIT%&8)'
  Wenn0: '%PREFIX% %PLAYER% &ehat den Server verlassen. &8(&a0&8/&a%LIMIT%&8)'
Join:
  Wenn23: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a24&8/&a%LIMIT%&8)'
  Wenn22: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a23&8/&a%LIMIT%&8)'
  Wenn21: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a22&8/&a%LIMIT%&8)'
  Wenn20: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a21&8/&a%LIMIT%&8)'
  Wenn19: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a20&8/&a%LIMIT%&8)'
  Wenn18: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a19&8/&a%LIMIT%&8)'
  Wenn17: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a18&8/&a%LIMIT%&8)'
  Wenn16: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a17&8/&a%LIMIT%&8)'
  Wenn15: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a16&8/&a%LIMIT%&8)'
  Wenn14: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a15&8/&a%LIMIT%&8)'
  Wenn13: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a14&8/&a%LIMIT%&8)'
  Wenn12: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a13&8/&a%LIMIT%&8)'
  Wenn11: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a12&8/&a%LIMIT%&8)'
  Wenn10: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a11&8/&a%LIMIT%&8)'
  Wenn9: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a10&8/&a%LIMIT%&8)'
  Wenn8: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a9&8/&a%LIMIT%&8)'
  Wenn7: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a8&8/&a%LIMIT%&8)'
  Wenn6: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a7&8/&a%LIMIT%&8)'
  Wenn5: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a6&8/&a%LIMIT%&8)'
  Wenn4: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a5&8/&a%LIMIT%&8)'
  Wenn3: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a4&8/&a%LIMIT%&8)'
  Wenn2: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a3&8/&a%LIMIT%&8)'
  Wenn1: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a2&8/&a%LIMIT%&8)'
  Wenn0: '%PREFIX% %PLAYER% &ehat den Server betreten. &8(&a1&8/&a%LIMIT%&8)'
Countdown: ' Die Spielphase startet in &a%COUNT%&7 Sekunden '
Randomtod:
  1: '%PLAYER% &6ist auf Rewis Rotze ausgerutscht'
  2: '%PLAYER% &6hat den Boden nicht gesehen'
  3: '%PLAYER% &6ist nun an einem besseren Ort'
  4: '%PLAYER% &6ist weg vom Fenster'
  5: '%PLAYER% &6ist vom Himmel gefallen'
  6: '%PLAYER% &6ist nun Matsch'
  7: '%PLAYER% &6hat keinen Block gefunden'
  8: '%PLAYER% &6hat den Skill zuhause gelassen'
  9: '%PLAYER% &6hat den Skill zuhause gelassen'
  10: '%PLAYER% &6ist geflogen'
  11: '%PLAYER% &6der Sensemann nahm ihn mit'
  12: '%%PLAYER% &6ist ne missgeburt'
start:
  limit: 12
  max: 24
Scoreboard:
  title: '&3JumpDown'
  0: '&6rewinside.tv'
