version: 1.0
author: MrWoopie
name: JumpDown
main: JumpDown.Main
commands:
     arena1:
          description:
          usage: 
     arena2:
          description:
          usage:  
     arena3:
          description:
          usage:          
     lobby:
          description:
          usage: 
     fertig:
          description:
          usage:    
     boden1:
          description:
          usage:    
     boden2:
          description:
          usage:               
     boden3:
          description:
          usage:  
     start:
          description:
          usage:  